### ISSUE TITLE
你好，请问这篇论文现在在哪里可以看到阿

### ISSUE THREAD

**Issue by lalalalala7** [ylqi/GL-RG#1]

**Comment by ylqi** [comment]
Paper will be available when our final paper is ready.

**Comment by lalalalala7** [comment]
ok,thank you



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月29日(周五) 上午9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ylqi/GL-RG] 你好，请问这篇论文现在在哪里可以看到阿 (Issue #1)




 
Paper will be available when our final paper is ready.
