### ISSUE TITLE
about pretrained models

### ISSUE THREAD

**Issue by Dorothylyly** [ylqi/GL-RG#2]
Hi,
I notice you said "Our long-range encoder is pre-trained on the video-to-words dataset (k=300 words) extracted from MSR-VTT or MSVD" in your paper, I wanna to know whether the whole datasets(train, valid, test) were used in your pretraining phase.  If so, I think it will lead to serious information leakage. Could you please release your pretraining code? thx : ).

**Comment by ylqi** [comment]
Thanks for your interest in our work. The long-range encoder pretraining ONLY uses the train split of the dataset. The pretraining code will be available as soon as going through the code collation. As a plug-and-play module, the structure of the long-range encoder is very flexible, you can easily reproduce it with any similar network you want.

**Comment by Dorothylyly** [comment]
Awesome！！！！Thanks for your reply！
