### ISSUE TITLE
conda环境安装问题

### ISSUE THREAD

**Issue by xyc0833** [ylqi/GL-RG#9]

**Comment by xyc0833** [comment]
![image](https://user-images.githubusercontent.com/57979311/227391399-186abe59-4c1d-41cd-9ad4-fec7a9a9597d.png)
颜教授您好，不好意思想请教一下  安装过程中 python 版本过低 导致无法正确安装  然后我尝试了 安装python3.7的版本 发现代码中有使用到cPickle的包  只能使用python2.X的环境  这个包没有办法安装在Python3.0及以上的版本当中
环境安装这块有无其他的方案，谢谢？

**Comment by ylqi** [comment]
您好，
如果您想在Python3.X上运行代码，您可以尝试以下方式：
将
`import cPickle`
改成:
`import _pickle as cPickle`

**Comment by xyc0833** [comment]
好的  我 尝试一下  谢谢颜教授

**Comment by Zeyu1226-mt** [comment]
> 您想在Python3.X上运行代码，您可以尝试以下方式：
> 将

请问您在python3.7上成功运行了吗
